name: Deez Nutz
markdown: kramdown
baseurl: https://mcolvin.github.com/sham
permalink: /blog/:year/:month/:day/:title

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-mcolvin-github-io-sham-blog