
# Site settings
title: Stuff
email: mec685@msstate.edu
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts, code snippets, and a trail of internet breadcrumbs.
baseurl: "/sham" # the subpath of your site, e.g. /blog
url: "http://mcolvin.github.io/sham" # the base hostname & protocol for your site
github_username:  mcolvin

# Build settings
markdown: kramdown
permalink: /sham/blog/:year/:month/:day/:title